title: K. S.
author: Karel Suchomel
email: karelsuchomel@windowslive.com
description: >- # this means to ignore newlines until "baseurl:"
  It's like we went for a beer together and I was only one talking and there was no beer.
keywords: Karel Suchomel, Krysa, has still not figured it out, likes DISCO minus Michal David
url: "http://karelsuchomel.cz" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:title:output_ext
theme:

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache