title: Karel Suchomel - personal site
author: Karel Suchomel
email: karelsuchomel@windowslive.com
description: >- # this means to ignore newlines until "baseurl:"
  Here I share what my dreams are, and what my heart tells me is important.
keywords: Karel Suchomel, Font-end, Koder, Web designer, School websites, School tools, Tools for schools
baseurl: "/personal-site"
url: "https://karelsuchomel.cz/" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:title:output_ext

# Build settings
markdown: kramdown
plugins:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache
# - vendor/bundle/
# - vendor/cache/
# - vendor/gems/
# - vendor/ruby/
